alter table PETCLINIC_PET add column GENERATION integer;
update PETCLINIC_PET set GENERATION = 10 where convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) < 152 ;
update PETCLINIC_PET set GENERATION = 20 where convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) >= 152 and convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) < 251 ;
update PETCLINIC_PET set GENERATION = 30 where convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) >= 252 and convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) < 387 ;
update PETCLINIC_PET set GENERATION = 40 where convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) >= 387 and convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) < 494 ;
update PETCLINIC_PET set GENERATION = 50 where convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) >= 494 and convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) < 650 ;
update PETCLINIC_PET set GENERATION = 60 where convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) >= 649 and convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) < 722 ;
update PETCLINIC_PET set GENERATION = 70 where convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) >= 721 and convert(IDENTIFICATION_NUMBER, SQL_NUMERIC) < 810 ;
alter table PETCLINIC_PET alter column GENERATION set not null ;
